-- CREATE TABLE
CREATE TABLE B_NBYJ_RECIEVE
(
  N_XH     VARCHAR2(8) NOT NULL,
  N_NBYJXH NUMBER(8),
  C_JSR    VARCHAR2(3000),
  C_ZT     CHAR(1),
  C_LX     CHAR(1)
)
TABLESPACE DCP
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 16
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE B_NBYJ_RECIEVE
  IS '内部邮件-接收人';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN B_NBYJ_RECIEVE.N_XH
  IS '序号';
COMMENT ON COLUMN B_NBYJ_RECIEVE.C_JSR
  IS '接收用户';
COMMENT ON COLUMN B_NBYJ_RECIEVE.C_ZT
  IS '状态';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE B_NBYJ_RECIEVE
  ADD CONSTRAINT PK_B_NBYJ_RECIEVE PRIMARY KEY (N_XH)
  USING INDEX 
  TABLESPACE DCP
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

  -- CREATE SEQUENCE 
CREATE SEQUENCE SEQ_B_NBYJ_RECIEVE
MINVALUE 10000
MAXVALUE 99999
START WITH 10000
INCREMENT BY 1
CACHE 20;