
  CREATE TABLE B_CLSQ (
  		N_XH NUMBER(6),
  		N_CLLBXH NUMBER(6),
		C_YHID VARCHAR2(30),
		C_SQSY VARCHAR2(3000),
		D_CCSJ DATE,
		D_GDSJ DATE,
		C_SFSH CHAR(1),
		C_SHR VARCHAR2(30),
		C_SHJG CHAR(1),
		D_SHSJ DATE,
		D_DJ DATE
	)
	TABLESPACE DCP
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 16K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
  
  -- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE B_CLSQ
  IS '车辆申请表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN B_CLSQ.N_XH
  IS '序号';
COMMENT ON COLUMN B_CLSQ.N_CLLBXH
  IS '车辆类别序号';
COMMENT ON COLUMN B_CLSQ.C_YHID
  IS '用户';
COMMENT ON COLUMN B_CLSQ.D_GDSJ
  IS '归队日期';
COMMENT ON COLUMN B_CLSQ.D_CCSJ
  IS '出发日期';
COMMENT ON COLUMN B_CLSQ.C_SQSY
  IS '申请事由';
COMMENT ON COLUMN B_CLSQ.C_SHR
  IS '审核人';
COMMENT ON COLUMN B_CLSQ.D_SHSJ
  IS '审核日期';
COMMENT ON COLUMN B_CLSQ.C_SHJG
  IS '审核结果';
COMMENT ON COLUMN B_CLSQ.D_DJ
  IS '登记日期';
  
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE B_CLSQ
  ADD CONSTRAINT PK_B_CLSQ PRIMARY KEY (N_XH)
  USING INDEX 
  TABLESPACE DCP
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

 
--SEQUENCE
CREATE SEQUENCE SEQ_B_CLSQ
MINVALUE 100000
MAXVALUE 999999
START WITH 100000
INCREMENT BY 1
CACHE 20;
 