
--取车牌号码
CREATE OR REPLACE FUNCTION FUN_GET_CPHM(N_CPXH NUMBER) RETURN VARCHAR2 
IS
     RES_NAME VARCHAR2(200);
BEGIN
      SELECT C_CPHM INTO RES_NAME FROM B_CLLB WHERE N_XH = N_CPXH;
      RETURN RES_NAME;
END;
/

--取网址分类名称
CREATE OR REPLACE FUNCTION FUN_GET_WZLB(N_LBXH NUMBER) RETURN VARCHAR2 

IS
     RES_NAME VARCHAR2(200);
BEGIN
      SELECT C_LBMC INTO RES_NAME FROM B_WZLB WHERE N_XH = N_LBXH;
      RETURN RES_NAME;
END;
/

--取用户名称
CREATE OR REPLACE FUNCTION FUN_GET_YHMC(C_YHID VARCHAR2) RETURN VARCHAR2
IS
     RES_NAME VARCHAR2(200);
BEGIN
      SELECT C_XM INTO RES_NAME FROM B_YH WHERE USER_ID = C_YHID;
      RETURN RES_NAME;
END;
/
