
--取车牌号码
CREATE OR REPLACE FUNCTION FUN_GET_CPHM(N_CPXH NUMBER) RETURN VARCHAR2 
IS
     RES_NAME VARCHAR2(200);
BEGIN
      SELECT C_CPHM INTO RES_NAME FROM B_CLLB WHERE N_XH = N_CPXH;
      RETURN RES_NAME;
END;
/

--取网址分类名称
CREATE OR REPLACE FUNCTION FUN_GET_WZLB(N_LBXH NUMBER) RETURN VARCHAR2 

IS
     RES_NAME VARCHAR2(200);
BEGIN
      SELECT C_LBMC INTO RES_NAME FROM B_WZLB WHERE N_XH = N_LBXH;
      RETURN RES_NAME;
END;
/

--代码名称
CREATE OR REPLACE FUNCTION FUN_GET_DM_MC(C_BXH VARCHAR,C_DM VARCHAR) RETURN VARCHAR2

IS
     RES_NAME VARCHAR2(200);
BEGIN
      SELECT C_MC INTO RES_NAME FROM D_DM WHERE C_BXH = C_BXH AND C_DM=C_DM;
      RETURN RES_NAME;
END;
/