-- CREATE TABLE
CREATE TABLE B_CLLB
(
  N_XH    NUMBER(8) NOT NULL,
  C_CPHM  VARCHAR2(30),
  C_YHZID NUMBER(10),
  D_DJ    DATE
)
TABLESPACE DCP
  PCTFREE 10
  PCTUSED 40
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 16K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE B_CLLB
  IS '车辆类别表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN B_CLLB.N_XH
  IS '序号';
COMMENT ON COLUMN B_CLLB.C_CPHM
  IS '车辆号码';
COMMENT ON COLUMN B_CLLB.C_YHZID
  IS '用户组';
COMMENT ON COLUMN B_CLLB.D_DJ
  IS '登记日期';
  
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE B_CLLB
  ADD CONSTRAINT PK_B_CLLB PRIMARY KEY (N_XH)
  USING INDEX 
  TABLESPACE DCP
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

 
--SEQUENCE
create sequence SEQ_B_CLLB
minvalue 1000
maxvalue 9999
start with 1000
increment by 1
cache 20;
 